= 1장 스프링 속으로

:icons: font
:Author: Byeongsoon Jang
:Email: byeongsoon@wisoft.io
:Date: 2018.08.06
:Revision: 1.0

spring in action - 크레이그 월즈 지음

* 1.1 자바 개발 간소화
* 1.2 빈을 담는 그릇, 컨테이너
* 1.3 스프링 현황
* 1.4 스프링의 새로운 기능

Byeongsoon Jang<byeongsoon@wisoft.io>

|===
|===

==== 1.1 자바 개발 간소화

스프링은 로드 존슨(Rod Johnson)의 책 <Expert One-on-One: J2EE Design and Developement>를 통해 소개된 오픈 소스 프레임워크로서 엔터프라이즈 애플리케이션 개발의 복잡함을 해소하기 위해 만들어졌다.

* 스프링은 EJB로만 할 수 있었던 작업을 평범한 자바빈을 사용해 가능케 한다.(link://http://tomee.apache.org/ejb-2.1-compatibility-example.html[EJB 2.1 Example])
** 스프링이 서버 측 개발에만 유용한 것은 아니다.
* 스프링을 사용하는 모든 자바 애플리케이션은 간소함, 테스트 용이성, 낮은 결합도라는 이득을 얻었다.
* 스프링이 애플리케이션 컴포넌트를 참조하면서 빈(bean)과 자바빈(JavaBean)을 사용하지만 반드시 link:https://www.oracle.com/technetwork/articles/javaee/spec-136004.html[자바빈의 스펙]을 따라야 하는 것을 의미하지는 않는다.
** 스프링 컴포넌트는 POJO 타입을 가진다.

====
스프링을 이용하면 테스트가 용이한 이유,

스프링의 DI를 이용하면 테스트시 의존하는 객체의 기능이 완전하게 완성되지 않아도 애플리케이션 로직이 기대하는 인터페이스를 구현하는 'mock' 객체를 작성하여 테스트를 할 수 있기 때문에 테스트가 용이하다고 한다.

이는 DI의 장점이자 스프링의 장점이다.
====

====
자바빈 스펙 예시,

* 멤버변수마다 별도의 get/set 메소드가 존재해야 한다.
** get 메소드는 매개변수가 존재하지 않아야 한다.
** set 메소드는 반드시 하나 이상의 매개변수가 존재해야 한다.
* 생성자는 기본 생성자를 반드시 포함해서 존재해야 한다.
** 생성자를 기술하지 않으면 자동 생성되므로 다른 생성자 없는 경우 기본 생성자 생략 가능.

* 접근 제어자
** Class : public
** field : private
** constructor : public
** getter/setter : public

* 패키지를 설정해야 한다
** 관리 목적으로
====

[TIP]
====
용어 설명

EJB : Enterprise JavaBean

POJO : Plain Old Java Object
====

* 자바 복잡도 간소화를 지원하기 위해 스프링은 네 가지 주요 전략을 사용한다.
** POJO를 이용한 가볍고 비침투적 개발
** DI와 인터페이스 지향을 통한 느슨한 결합도
** 애스펙트와 공통 규약을 통한 선언적 프로그래밍
** 애스펙트와 템플릿을 통한 반복적인 코드 제거

[TIP]
====
비침투적 개발이란, 바탕이 되는 기술을 사용하는 클래스, 인터페이스, API 등을 코드에 직접 나타내지 않는 방법이다.
복잡함을 분리할 수 있다.
====

* 스프링은 API를 이용하여 애플리케이션 코드의 분산을 가능한 한 막는다.
** 스프링은 스프링에 특화된 인터페이스 구현이나 스프링 자체에 의존성이 높은 클래스 확장을 거의 요구하지 않는다.

* DI를 활용한 조립
** DI를 적용해 보면 코드가 훨씬 더 간단해지고, 이해하기 쉬우며, 테스트하기도 쉬워진다.
** 결합도가 높은 코드는 한편으로 테스트와 재활용이 어렵고 이해하기도 어려우며, 오류를 하나 수정하면 다른 오류가 발생하는 경향이 있다.

.예제
====

간단한 계산기 프로젝트를 통해서 DI에 대해 간단히 알아본다.

.Calculator.java
[source, java]
----
public class Calculator {

  public void addition(int f, int s) {
    System.out.println("addition()");
    int result = f + s;
    System.out.println(f + " + " + s + " = " + result);
  }

  public void subtraction(int f, int s) {
    System.out.println("subtraction()");
    int result = f - s;
    System.out.println(f + " - " + s + " = " + result);
  }

  public void multiplication(int f, int s) {
    System.out.println("multiplication()");
    int result = f * s;
    System.out.println(f + " x " + s + " = " + result);
  }

  public void division(int f, int s) {
    System.out.println("division()");
    int result = f / s;
    System.out.println(f + " / " + s + " = " + result);
  }

}
----

.DI가 적용되지 않은 MyCalculator.java
[source, java]
----
public class MyCalculator {

  private Calculator calculator;
  private int firstNum;
  private int secondNum;

  public MyCalculator(){
    this.calculator = new Calculator(); // Calculator에 강하게 결합!!
  }

  public void add() {
    calculator.addition(firstNum, secondNum);
  }

  public void sub() {
    calculator.subtraction(firstNum, secondNum);
  }

  public void mul() {
    calculator.multiplication(firstNum, secondNum);
  }

  public void div() {
    calculator.division(firstNum, secondNum);
  }


  public Calculator getCalculator() {
    return calculator;
  }

  public int getFirstNum() {
    return firstNum;
  }

  public int getSecondNum() {
    return secondNum;
  }

  public void setCalculator(Calculator calculator) {
    this.calculator = calculator;
  }

  public void setFirstNum(int firstNum) {
    this.firstNum = firstNum;
  }

  public void setSecondNum(int secondNum) {
    this.secondNum = secondNum;
  }

}
----

====

* 애플리케이션 컴포넌트 간의 관계를 정리하는 것을 와이어링(wiring)이라고 한다.
** 스프링에서 컴포넌트를 와이어링 하는 방법은 여러 가지가 있지만 일반적인 방법은 xml을 이용하는 방법이다.

* 자세한 내용은 2장에서 스프링이 빈을 와이어링하는 또 다른 방법과 스프링이 자동으로 빈을 찾고 빈의 관계를 생성하는 방법을 살펴본다.

===== AOP

* 애스펙트 지향 프로그래밍은 애플리케이션 전체에 걸쳐 사용되는 기능을 재사용할 수 있는 컴포넌트에 담는다.

* AOP는 시스템 서비스를 모듈화해서 컴포넌트에 선언적으로 적용한다.

====
AOP는 보통 '제 3자의 관점으로 바라보자'

즉, 대상을 바라보는 방향을 바꿔보자라는 이야기다.

주로 공통된 메소드 실행 전, 후로 공통된 기능이나 실행시간 측정, 로그 기록등에 대한 것을 이 AOP를 사용한다.

.AOP 예시
[source, xml]
----
<bean id="aopTest" class="wisoft.io.AOPTest"/>

  <aop:config>
      <aop:aspect id="calculatorAOP" ref="aopTest">
          <aop:pointcut id="aopPointCut" expression="execution(public * wisoft.io.MyCalculator.*(..))"/>
          <aop:around method="calculatorBefore" pointcut-ref="aopPointCut" />

          <aop:before method="calculatorBefore" pointcut-ref="aopPointCut"/>

          <aop:after method="caculatorAfter" pointcut-ref="aopPointCut"/>
      </aop:aspect>
  </aop:config>
----
====

==== 1.2 빈을 담는 그릇, 컨테이너

* 스프링 기반 애플리케이션에서는 스프링 컨테이너 안에서 객체가 태어나고, 자라고, 소멸한다.
** 스프링 컨테이너는 객체를 생성하고 서로 엮어주고, 이들의 전체 생명주기를 관리한다.

===== 빈의 생명주기(Bean Life Cycle)

====

1. 빈 객체 생성
2. BeanNameAware.setBeanName()
3. BeanFactoryAware.setBeanFactory()
4. BeanPostProcessor의 초기화 전처리
5. 커스텀 init - method
6. InitializingBean.afterPropertiesSet()
7. BeanPostProcessor의 초기화 후처리
8. 빈 객체 사용
9. DisposableBean.destroy()
10. 커스텀 destroy - method

====

* 스프링 컨테이너는 여러 가지가 있다.
** 여러 컨테이너 구현체가 존재하며, 이들은 크게 두 가지로 분류된다.
*** 빈 팩토리 : DI에 대한 기본적인 지원을 제공하는 가장 단순한 컨테이너 이다.
*** 애플리케이션 컨텍스트 : 빈 팩토리를 확장해 프로퍼티 파일에 텍스트 메시지를 읽고 해당 이벤트 리스너에 대한 애플리케이션 이벤트 발행 같은 애플리케이션 프레임워크 서비스를 제공하는 컨테이너다.

====
*link:http://flyburi.com/277[빈 팩토리와 애플리케이션 컨텍스트 비교]*

* 빈 팩토리 : 팩토리 디자인 패턴을 구현한 것, 빈 팩토리는 빈을 생성하고 분배하는 책임을 지는 클래스

* 애플리케이션 컨텍스트 : 빈 팩토리와 유사한 기능을 제공하지만 좀 더 많은 기능을 제공하는 ApplicationContext

====

==== 1.3 스프링 현황

* 스프링 프레임워크는 스프링이 자바 개발을 쉽게 할 수 있는 여러 가지 방법을 제공한다.
** 스프링 모듈
*** 코어 스프링 컨테이너
*** 스프링의 AOP 모듈
*** 데이터 액세스와 통합
*** 웹과 리모팅
*** 인스트루멘테이션
*** 테스팅

** 스프링 포트폴리오 - 스프링 포트폴리오에는 코어 스프링 프레임워크와 서로 연관되어 구축된 다양한 프레임워크와 라이브러리가 있다.
*** 스프링 웹 플로
*** 스프링 웹 서비스
*** 스프링 시큐리티
*** 스프링 인티그레이션
*** 스프링 배치
*** 스프링 데이터
*** 스프링 소셜
*** 스프링 모바일
*** 안드로이드용 스프링
*** 스프링 부트

==== 1.4 스프링의 새로운 기능

스프링의 새로운 기능은 책을 참고하거나
link:https://spring.io/[여기]를 참고.
